# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-19 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(blank=True, max_length=255, null=True)),
                ('cate_log_name', models.CharField(max_length=255)),
                ('cate_log_id', models.CharField(blank=True, max_length=255, null=True)),
                ('evaluation', models.FloatField()),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('is_use', models.IntegerField()),
                ('loc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('loc_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('on_decade', models.CharField(blank=True, max_length=255, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_class_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_class_id', models.CharField(blank=True, max_length=255, null=True)),
                ('type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('update_time', models.CharField(blank=True, max_length=255, null=True)),
                ('is_vip', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_film',
            },
        ),
    ]
