# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-20 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='cate_log_name',
            new_name='cate1_log_name',
        ),
    ]
